// Generated by https://quicktype.io

namespace OAconsole
{
    using Newtonsoft.Json;

    public partial class ConfigList
    {
        [JsonProperty("result")]
        public Result Result { get; set; }

        [JsonProperty("token")]
        public string Token { get; set; }

        [JsonProperty("resultType")]
        public string ResultType { get; set; }

        [JsonProperty("resultMessage")]
        public object ResultMessage { get; set; }
    }
}
