//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTable
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> B_OrderTime { get; set; }
        public string B_Name { get; set; }
        public string B_SalesName { get; set; }
        public string B_AgentName { get; set; }
        public string B_Product { get; set; }
        public string B_ProductDes { get; set; }
        public string B_ItemCode { get; set; }
        public string B_SPCode { get; set; }
        public Nullable<int> B_Count { get; set; }
        public Nullable<System.DateTime> P_Replytime { get; set; }
        public string P_DelieverNote { get; set; }
        public string P_DeliverTime { get; set; }
        public string C_Note { get; set; }
        public string C_Priority { get; set; }
        public string C_LastMac { get; set; }
        public string B_ItemType { get; set; }
    }
}
