// Generated by https://quicktype.io

namespace OAconsole
{
    using Newtonsoft.Json;

    public partial class ConfigList
    {
        public static ConfigList FromJson(string json) => JsonConvert.DeserializeObject<ConfigList>(json, OAconsole.Converter.Settings);
    }
}
