// Generated by https://quicktype.io

namespace OAconsole
{
    using Newtonsoft.Json;

    public partial class Creator
    {
        [JsonProperty("user_name")]
        public string UserName { get; set; }

        [JsonProperty("user_id")]
        public long UserId { get; set; }
    }
}
