// Generated by https://quicktype.io

namespace QuickType
{
    using System;
    using Newtonsoft.Json;

    public partial class PlatformPartList
    {
        [JsonProperty("part_name")]
        public PartName PartName { get; set; }

        [JsonProperty("part_id")]
        public long PartId { get; set; }

        [JsonProperty("supplier_model")]
        public SupplierModel SupplierModel { get; set; }

        [JsonProperty("part_category_id")]
        public object PartCategoryId { get; set; }

        [JsonProperty("operator_id")]
        public long OperatorId { get; set; }

        [JsonProperty("sale_part_price")]
        public double SalePartPrice { get; set; }

        [JsonProperty("part_type_name")]
        public PartTypeName PartTypeName { get; set; }

        [JsonProperty("material_part_price")]
        public double MaterialPartPrice { get; set; }

        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("backlog_flg")]
        public long BacklogFlg { get; set; }

        [JsonProperty("product_type_id")]
        public long ProductTypeId { get; set; }

        [JsonProperty("shelf_life")]
        public long? ShelfLife { get; set; }

        [JsonProperty("part_type_id")]
        public long PartTypeId { get; set; }

        [JsonProperty("part_type_notes")]
        public string PartTypeNotes { get; set; }

        [JsonProperty("part_is_deleted")]
        public long PartIsDeleted { get; set; }

        [JsonProperty("is_promotional")]
        public long IsPromotional { get; set; }

        [JsonProperty("product_platform_id")]
        public ProductPlatformId ProductPlatformId { get; set; }

        [JsonProperty("part_type_type")]
        public long PartTypeType { get; set; }

        [JsonProperty("whole_sale_flg")]
        public long WholeSaleFlg { get; set; }

        [JsonProperty("creator_id")]
        public long CreatorId { get; set; }

        [JsonProperty("sale_status")]
        public long SaleStatus { get; set; }

        [JsonProperty("is_deleted")]
        public long IsDeleted { get; set; }

        [JsonProperty("update_time")]
        public DateTimeOffset UpdateTime { get; set; }

        [JsonProperty("bulk_sale_flg")]
        public long BulkSaleFlg { get; set; }

        [JsonProperty("create_time")]
        public DateTimeOffset CreateTime { get; set; }

        [JsonProperty("part_code")]
        public PartCode PartCode { get; set; }

        [JsonProperty("notes")]
        public Notes Notes { get; set; }
    }
}
