// Generated by https://quicktype.io

namespace OAconsole
{
    using Newtonsoft.Json;

    public partial class ProductConfigDataList
    {
        [JsonProperty("part_name")]
        public string PartName { get; set; }

        [JsonProperty("part_id")]
        public long PartId { get; set; }

        [JsonProperty("supplier_model")]
        public string SupplierModel { get; set; }

        [JsonProperty("part_type_name")]
        public string PartTypeName { get; set; }

        [JsonProperty("part_type_notes")]
        public string PartTypeNotes { get; set; }

        [JsonProperty("product_id")]
        public long ProductId { get; set; }

        [JsonProperty("material_part_price")]
        public double MaterialPartPrice { get; set; }

        [JsonProperty("product_config_id")]
        public long ProductConfigId { get; set; }

        [JsonProperty("sale_part_price")]
        public double SalePartPrice { get; set; }

        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("part_code")]
        public string PartCode { get; set; }

        [JsonProperty("notes")]
        public string Notes { get; set; }

        [JsonProperty("sale_status")]
        public long SaleStatus { get; set; }
    }
}
