// Generated by https://quicktype.io

namespace QuickType
{
    using System;
    using Newtonsoft.Json;

    public partial class Result
    {
        [JsonProperty("quotation_serial_number")]
        public string QuotationSerialNumber { get; set; }

        [JsonProperty("quotation_id")]
        public long QuotationId { get; set; }

        [JsonProperty("discounted_product_config_price")]
        public double DiscountedProductConfigPrice { get; set; }

        [JsonProperty("opportunity_name")]
        public object OpportunityName { get; set; }

        [JsonProperty("contains_all_product_type")]
        public bool ContainsAllProductType { get; set; }

        [JsonProperty("owner_name")]
        public RName OwnerName { get; set; }

        [JsonProperty("contract_approval_id")]
        public object ContractApprovalId { get; set; }

        [JsonProperty("operator_id")]
        public long OperatorId { get; set; }

        [JsonProperty("total_cost_price")]
        public double TotalCostPrice { get; set; }

        [JsonProperty("current_approval_user_name")]
        public RName CurrentApprovalUserName { get; set; }

        [JsonProperty("quotation_name")]
        public string QuotationName { get; set; }

        [JsonProperty("opportunity_owner_id")]
        public object OpportunityOwnerId { get; set; }

        [JsonProperty("creator")]
        public Creator Creator { get; set; }

        [JsonProperty("quotation_notes")]
        public object QuotationNotes { get; set; }

        [JsonProperty("discount_price")]
        public double DiscountPrice { get; set; }

        [JsonProperty("product_config_list")]
        public ProductConfigList[] ProductConfigList { get; set; }

        [JsonProperty("quotation_status")]
        public long QuotationStatus { get; set; }

        [JsonProperty("spare_part_config_data_list")]
        public object[] SparePartConfigDataList { get; set; }

        [JsonProperty("contract_code")]
        public object ContractCode { get; set; }

        [JsonProperty("operator_name")]
        public RName OperatorName { get; set; }

        [JsonProperty("discount_rate")]
        public double DiscountRate { get; set; }

        [JsonProperty("opportunity_id")]
        public object OpportunityId { get; set; }

        [JsonProperty("third_party_product_list")]
        public object[] ThirdPartyProductList { get; set; }

        [JsonProperty("discounted_third_price")]
        public double DiscountedThirdPrice { get; set; }

        [JsonProperty("approval_status")]
        public long ApprovalStatus { get; set; }

        [JsonProperty("contract_approval_status")]
        public object ContractApprovalStatus { get; set; }

        [JsonProperty("customer_name")]
        public object CustomerName { get; set; }

        [JsonProperty("contract_id")]
        public object ContractId { get; set; }

        [JsonProperty("approval_id")]
        public long ApprovalId { get; set; }

        [JsonProperty("total_price")]
        public double TotalPrice { get; set; }

        [JsonProperty("operator")]
        public Creator Operator { get; set; }

        [JsonProperty("creator_id")]
        public long CreatorId { get; set; }

        [JsonProperty("spare_part_service_list")]
        public object[] SparePartServiceList { get; set; }

        [JsonProperty("is_deleted")]
        public long IsDeleted { get; set; }

        [JsonProperty("update_time")]
        public DateTimeOffset UpdateTime { get; set; }

        [JsonProperty("approval_need_user_type")]
        public long ApprovalNeedUserType { get; set; }

        [JsonProperty("owner")]
        public Creator Owner { get; set; }

        [JsonProperty("create_time")]
        public DateTimeOffset CreateTime { get; set; }

        [JsonProperty("owner_id")]
        public long OwnerId { get; set; }

        [JsonProperty("creator_name")]
        public RName CreatorName { get; set; }

        [JsonProperty("discounted_spare_price")]
        public double DiscountedSparePrice { get; set; }
    }
}
