// Generated by https://quicktype.io

namespace OAconsole
{
    using Newtonsoft.Json;

    public static class Serialize
    {
        public static string ToJson(this ConfigList self) => JsonConvert.SerializeObject(self, OAconsole.Converter.Settings);
    }
}
